apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: 192.168.100.253
    path: /mnt/media-server/
    readOnly: no
  claimRef:
    name: media-server-pvc
    namespace: media-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-pvc
  namespace: media-server
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: "media-server"
    meta.helm.sh/release-namespace: "media-server"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "500Gi"
  storageClassName: ""
