{{ if .Values.qbit.enabled }}
---
## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbit-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbit
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: qbit
    spec:
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: qbit-config
          image: "{{ .Values.qbit.container.image }}:{{ .Values.qbit.container.tag | default .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.qbit.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          ports:
            - name: qbit-port
              containerPort: {{ .Values.qbit.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.qbit.volume }}
            - name: {{ .Values.qbit.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/qbit"
          {{- end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}"
            - name: mediaserver-volume
              mountPath: "/tv"
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
            - name: mediaserver-volume
              mountPath: "/movies"
              subPath: "{{ .Values.general.storage.subPaths.movies }}"
          {{- with .Values.qbit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{ if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{ else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{ end }}
        {{- if .Values.qbit.volume }}
        - name: {{ .Values.qbit.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.qbit.volume.name }}
        {{- end }}
        # - name: init-files-qbit
        #   configMap:
        #     defaultMode: 493
        #     name: init-qbit-cm
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: qbit
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.qbit.service.type }}
  ports:
    - port: {{ .Values.qbit.service.port }}
      targetPort: {{ .Values.qbit.container.port }}
      protocol: TCP
{{ if eq .Values.qbit.service.type "NodePort" }}
      nodePort: {{ .Values.qbit.service.nodePort }}
{{ end }}
      name: qbit-port
  selector:
    app: qbit
---
{{ if .Values.qbit.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: qbit-lb
  annotations:
    {{- include .Values.qbit.service.extraLBService.annotations . | nindent 4 }}
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.qbit.service.port }}
      targetPort: {{ .Values.qbit.container.port }}
      protocol: TCP
      name: qbit-port
  selector:
    app: qbit
{{ end }}
---
### INGRESS ###
{{ if .Values.qbit.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbit
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.qbit.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if .Values.qbit.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.qbit.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.qbit.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: qbit
                port:
                  number: {{ .Values.qbit.service.port }}
{{ end }}
{{ end }}
